name: Build

on:
  push:
    branches: [ main ]

jobs:
  bundle-rollup:
    name: 'Bundle to single .cjs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Bundle to single .cjs'
        run: |
          mkdir -p build
          cp index.js build/index.cjs
      - name: 'Upload .cjs artifact'
        uses: actions/upload-artifact@v4
        with:
          name: bundle-cjs
          path: build/index.cjs
          retention-days: 1

  build-linux-binary:
    needs: bundle-rollup
    name: 'Build linux binary'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download .cjs artifact'
        uses: actions/download-artifact@v4
        with:
          name: bundle-cjs
          path: build/
      - name: 'Build linux binary'
        run: cp build/index.cjs build/index-linux
      - name: 'Upload binary artifact'
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: build/index-linux
          retention-days: 1

  build-mac-binary:
    needs: bundle-rollup
    name: 'Build mac binary'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download .cjs artifact'
        uses: actions/download-artifact@v4
        with:
          name: bundle-cjs
          path: build/
      - name: 'Build mac binary'
        run: cp build/index.cjs build/index-mac
      - name: 'Upload binaries artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: mac-binaries
          path: build/index-mac
          retention-days: 1

  build-windows-binary:
    needs: bundle-rollup
    name: 'Build windows binary'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download .cjs artifact'
        uses: actions/download-artifact@v4
        with:
          name: bundle-cjs
          path: build/
      - name: 'Build windows binary'
        run: cp build/index.cjs build/index-win.exe
      - name: 'Upload binaries artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: build/index-win.exe
          retention-days: 1

  create-archives:
    needs:
      - build-linux-binary
      - build-mac-binary
      - build-windows-binary
    name: 'Create .tar.gz and .zip archives'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download binaries artifacts'
        uses: actions/download-artifact@v4
        with:
          pattern: *-binary
          path: build/
      - name: 'foo'
        run: |
          tar czf index-linux.tar.gz index-linux
          tar czf index-mac.tar.gz index-mac
          zip -r index-win.zip index-win.exe
        working-directory: build
      - name: 'Upload archives artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: archives
          path: |
            build/index-linux.tar.gz
            build/index-mac.tar.gz
            build/index-win.zip
          retention-days: 1

  generate-checksums:
    needs: create-archives
    name: 'Generate checksums'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download archives artifacts'
        uses: actions/download-artifact@v4
        with:
          name: archives
          path: build/
      - name: 'foo'
        run: |
          sha256sum build/index-linux.tar.gz | cut -d' ' -f1 > build/index-linux.tar.gz.sha256
          sha256sum build/index-mac.tar.gz | cut -d' ' -f1 > build/index-mac.tar.gz.sha256
          sha256sum build/index-win.zip | cut -d' ' -f1 > build/index-win.zip.sha256
      - name: 'Upload checksums artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: |
            build/index-linux.tar.gz.sha256
            build/index-mac.tar.gz.sha256
            build/index-win.zip.sha256
          retention-days: 1
