name: Build RPM

on:
  push:
    branches:
      - main

env:
  RPM_GPG_PRIVATE_KEY: ${{ secrets.RPM_GPG_PRIVATE_KEY }}
  NFPM_PASSPHRASE: ${{ secrets.RPM_GPG_PASSPHRASE }}
  NFPM_VERSION: "2.43.0"
  RPM_FILENAME: "clever-tools-${{ github.ref_name }}.rpm"

jobs:
  build-rpm:
    name: 'Build .rpm'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Download nfpm'
        run: |
          curl -sL https://github.com/goreleaser/nfpm/releases/download/v${{ env.NFPM_VERSION }}/nfpm_${{ env.NFPM_VERSION }}_Linux_x86_64.tar.gz | tar -xz
          chmod +x nfpm
      - name: 'Build and sign RPM with nfpm'
        run: |
          echo "$RPM_GPG_PRIVATE_KEY" > /tmp/signing-key.asc
          ./nfpm package --config scripts/templates/nfpm.yaml --packager rpm --target ${{ env.RPM_FILENAME }}
        env:
          VERSION: ${{ github.ref_name }}
      - name: 'Upload RPM artifact'
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: ${{ env.RPM_FILENAME }}
          retention-days: 1
