name: Build

on:
  workflow_call:

jobs:

  bundle-cjs:
    name: Bundle single clever.cjs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install Node.js dependencies
        run: npm ci
      - name: Bundle to single clever.cjs
        run: npm run bundle-cjs
      - name: Upload bundle-cjs artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-cjs
          path: build/clever.cjs
          retention-days: 1

  build-linux:
    needs: bundle-cjs
    name: Build linux binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Download bundle-cjs artifact
        uses: actions/download-artifact@v4
        with: { name: bundle-cjs }
      - name: Build linux binary
        run: |
          echo pkg bla bla bla
          cp clever.cjs clever
      - name: Upload build-linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: clever
          retention-days: 1
#
#  build-mac:
#    needs: bundle-cjs
#    name: Build mac binary
#    runs-on: macos-14
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Download bundle-cjs artifact
#        uses: actions/download-artifact@v4
#        with: { name: bundle-cjs }
#      - name: Build mac binary
#        run: |
#          echo pkg bla bla bla
#          cp clever.cjs clever
#      - name: Upload build-mac artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: build-mac
#          path: clever
#          retention-days: 1
#
#  build-windows:
#    needs: bundle-cjs
#    name: Build windows binary
#    runs-on: windows-latest
#    steps:
#      - name: Checkout sources
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Download bundle-cjs artifact
#        uses: actions/download-artifact@v4
#        with: { name: bundle-cjs }
#      - name: Build windows binary
#        run: |
#          echo pkg bla bla bla
#          cp clever.cjs clever.exe
#      - name: Upload build-windows artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: build-windows
#          path: clever.exe
#          retention-days: 1
#
#  archives-checksums:
#    needs: [build-linux, build-mac, build-windows]
#    name: Create archives and checksums
#    runs-on: ubuntu-latest
#    steps:
#      - name: Download build artifacts
#        uses: actions/download-artifact@v4
#        with:
#          pattern: build-*
#      - name: Create .tar.gz and checksum file for linux
#        id: linux
#        working-directory: build-linux
#        run: |
#          tar czf clever-tools_linux.tar.gz clever
#          sha256sum clever-tools_linux.tar.gz > clever-tools_linux.tar.gz.sha256
#      - name: Create .tar.gz and checksum file for mac
#        id: mac
#        working-directory: build-mac
#        run: |
#          tar czf clever-tools_mac.tar.gz clever
#          sha256sum clever-tools_mac.tar.gz > clever-tools_mac.tar.gz.sha256
#      - name: Create .zip and checksum file for windows
#        id: windows
#        working-directory: build-windows
#        run: |
#          zip clever-tools_win.zip clever.exe
#          sha256sum clever-tools_win.zip > clever-tools_win.zip.sha256
#      - name: Upload linux archives
#        uses: actions/upload-artifact@v4
#        with:
#          name: archive-checksum-linux
#          path: |
#            build-linux/clever-tools_linux.tar.gz
#            build-linux/clever-tools_linux.tar.gz.sha256
#          retention-days: 1
#      - name: Upload mac archives
#        uses: actions/upload-artifact@v4
#        with:
#          name: archive-checksum-mac
#          path: |
#            build-mac/clever-tools_mac.tar.gz
#            build-mac/clever-tools_mac.tar.gz.sha256
#          retention-days: 1
#      - name: Upload windows archives
#        uses: actions/upload-artifact@v4
#        with:
#          name: archive-checksum-windows
#          path: |
#            build-windows/clever-tools_win.zip
#            build-windows/clever-tools_win.zip.sha256
#          retention-days: 1
