name: Build

on:
  push:
    branches: [ main ]

jobs:
  bundle-single-cjs:
    name: 'Bundle to single .cjs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Bundle to single .cjs'
        run: |
          mkdir -p build
          cp index.js build/index.cjs
      - name: 'Upload bundle-single-cjs artifact'
        uses: actions/upload-artifact@v4
        with:
          name: bundle-single-cjs
          path: build/index.cjs
          retention-days: 1

  build-linux:
    needs: bundle-single-cjs
    name: 'Build linux binary'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download bundle-single-cjs artifact'
        uses: actions/download-artifact@v4
        with:
          name: bundle-single-cjs
          path: build/
      - name: 'Build linux binary'
        run: cp build/index.cjs build/index-linux
      - name: 'Upload build-linux artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-linux
          path: build/index-linux
          retention-days: 1

  build-mac:
    needs: bundle-single-cjs
    name: 'Build mac binary'
    runs-on: macos-14
    steps:
      - name: 'Download bundle-single-cjs artifact'
        uses: actions/download-artifact@v4
        with:
          name: bundle-single-cjs
          path: build/
      - name: 'Build mac binary'
        run: cp build/index.cjs build/index-mac
      - name: 'Upload build-mac artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-mac
          path: build/index-mac
          retention-days: 1

  build-windows:
    needs: bundle-single-cjs
    name: 'Build windows binary'
    runs-on: windows-latest
    steps:
      - name: 'Download bundle-single-cjs artifact'
        uses: actions/download-artifact@v4
        with:
          name: bundle-single-cjs
          path: build/
      - name: 'Build windows binary'
        run: cp build/index.cjs build/index-win.exe
      - name: 'Upload build-windows artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: build/index-win.exe
          retention-days: 1

  archives-checksums:
    needs: [build-linux, build-mac, build-windows]
    name: 'Create archives and checksums'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download build artifacts'
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: build/
      - name: 'Create .tar.gz and checksum file for linux'
        run: |
          tar czf build/index-linux.tar.gz -C build index-linux
          sha256sum build/index-linux.tar.gz > build/index-linux.tar.gz.sha256
      - name: 'Create .tar.gz and checksum file for mac'
        run: |
          tar czf build/index-mac.tar.gz -C build index-mac
          sha256sum build/index-mac.tar.gz > build/index-mac.tar.gz.sha256
      - name: 'Create .zip and checksum file for windows'
        run: |
          zip -j build/index-win.zip build/index-win.exe
          sha256sum build/index-win.zip > build/index-win.zip.sha256
      - name: 'Upload archives'
        uses: actions/upload-artifact@v4
        with:
          name: archives-checksums
          path: |
            build/index-linux.tar.gz
            build/index-linux.tar.gz.sha256
            build/index-mac.tar.gz
            build/index-mac.tar.gz.sha256
            build/index-win.zip
            build/index-win.zip.sha256
          retention-days: 1

  publish-preview:
    needs: [archives-checksums]
    name: 'Publish Preview'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download archives'
        uses: actions/download-artifact@v4
        with:
          name: archives-checksums
          path: build/
      - name: 'List all artifacts'
        run: ls -la build/*
