name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Bundle JavaScript
      run: npx rollup --format=cjs --file=build/index.single.cjs index.js

    - name: Upload bundled JS
      uses: actions/upload-artifact@v4
      with:
        name: bundled-js
        path: build/index.single.cjs
        retention-days: 7

  build:
    needs: bundle
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            target: node22-linux
            output: hello-world-linux
            extension: ''
          - os: windows-latest
            platform: windows
            target: node22-win
            output: hello-world-win
            extension: '.exe'
          - os: macos-latest
            platform: macos-x64
            target: node22-macos-x64
            output: hello-world-macos
            extension: ''
          - os: macos-latest
            platform: macos-arm
            target: node22-macos-arm64
            output: hello-world-macos-arm
            extension: ''

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create build directory
      run: mkdir -p build
      shell: bash
      
    - name: Download bundled JS
      uses: actions/download-artifact@v4
      with:
        name: bundled-js
        path: build/

    - name: Run pkg command for ${{ matrix.platform }}
      run: npx @yao-pkg/pkg build/index.single.cjs -t ${{ matrix.target }} -o build/${{ matrix.output }}${{ matrix.extension }}

    - name: Verify binary execution
      shell: bash
      run: |
        chmod +x build/${{ matrix.output }}${{ matrix.extension }}
        ./build/${{ matrix.output }}${{ matrix.extension }}
        echo "✅ Binary executed successfully with exit code $?"

    - name: Upload ${{ matrix.platform }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output }}
        path: build/${{ matrix.output }}${{ matrix.extension }}
        retention-days: 7
