name: Preview

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  #BRANCH: ${{ github.event.pull_request.head.ref }}
  CC_CLEVER_TOOLS_PREVIEWS_CELLAR_KEY_ID: ${{ secrets.CC_CLEVER_TOOLS_PREVIEWS_CELLAR_KEY_ID }}
  CC_CLEVER_TOOLS_PREVIEWS_CELLAR_SECRET_KEY: ${{ secrets.CC_CLEVER_TOOLS_PREVIEWS_CELLAR_SECRET_KEY }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.ref_name || 'latest' }}

  publish:
    needs: build
    name: 'Publish preview'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download build artifacts'
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: build
          merge-multiple: true
      - name: 'List all artifacts'
        run: tree .
