name: Preview

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.ref_name }}

  publish:
    needs: build
    name: 'Publish preview'
    runs-on: ubuntu-latest
    env:
      VERSION: github.ref_name
    steps:
      - name: 'Download linux archive and checksum'
        uses: actions/download-artifact@v4
        with:
          name: archive-checksum-linux
          path: build/${{ env.VERSION }}/linux
      - name: 'Download mac archive and checksum'
        uses: actions/download-artifact@v4
        with:
          name: archive-checksum-mac
          path: build/${{ env.VERSION }}/mac
      - name: 'Download windows archive and checksum'
        uses: actions/download-artifact@v4
        with:
          name: archive-checksum-win
          path: build/${{ env.VERSION }}/win
      - name: 'List all artifacts'
        run: tree .
