name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.ref_name }}

  build-rpm:
    name: 'Build .rpm'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Download build-linux artifact'
        uses: actions/download-artifact@v4
        with:
          name: build-linux
          path: build
      - name: 'Build .rpm with nfpm'
        run: ./scripts/package-nfpm.js ${{ github.ref_name }} rpm
        env:
          RPM_GPG_PRIVATE_KEY: ${{ secrets.RPM_GPG_PRIVATE_KEY }}
          RPM_GPG_PASSPHRASE: ${{ secrets.RPM_GPG_PASSPHRASE }}
      - name: 'Upload .rpm artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-rpm
          path: build
          retention-days: 1

  build-deb:
    name: 'Build .deb'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Download build-linux artifact'
        uses: actions/download-artifact@v4
        with:
          name: build-linux
          path: build
      - name: 'Build .deb with nfpm'
        run: ./scripts/package-nfpm.js ${{ github.ref_name }} deb
      - name: 'Upload .deb artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build-deb
          path: build
          retention-days: 1

  publish-npm:
    name: 'Publish to npm'
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: 'Publish to npm'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  update-github-release:
    name: 'Update GitHub release'
    runs-on: ubuntu-latest
    needs: [ build, build-rpm, build-deb ]
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Download all build artifacts'
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: build
          merge-multiple: true
      - name: 'Upload artifacts to GitHub release'
        run: |
          gh release upload "${{ github.ref_name }}" build/${{ github.ref_name }}/linux/clever-tools-${{ github.ref_name }}_linux.tar.gz
          gh release upload "${{ github.ref_name }}" build/${{ github.ref_name }}/macos/clever-tools-${{ github.ref_name }}_macos.tar.gz
          gh release upload "${{ github.ref_name }}" build/${{ github.ref_name }}/win/clever-tools-${{ github.ref_name }}_win.zip
          gh release upload "${{ github.ref_name }}" build/${{ github.ref_name }}/clever-tools-${{ github.ref_name }}.deb
          gh release upload "${{ github.ref_name }}" build/${{ github.ref_name }}/clever-tools-${{ github.ref_name }}.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-cellar-archives:
    name: 'Publish archives to cellar'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Download all build artifacts'
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: build
          merge-multiple: true
      - name: 'TODO debug'
        run: tree
      - name: 'Publish archives to cellar'
        run: ./scripts/publish-cellar.js ${{ github.ref_name }} archives
        env:
          CC_CLEVER_TOOLS_RELEASES_CELLAR_BUCKET: ${{ secrets.CC_CLEVER_TOOLS_RELEASES_CELLAR_BUCKET }}
          CC_CLEVER_TOOLS_RELEASES_CELLAR_KEY_ID: ${{ secrets.CC_CLEVER_TOOLS_RELEASES_CELLAR_KEY_ID }}
          CC_CLEVER_TOOLS_RELEASES_CELLAR_SECRET_KEY: ${{ secrets.CC_CLEVER_TOOLS_RELEASES_CELLAR_SECRET_KEY }}

  publish-cellar-rpm:
    name: 'Publish .rpm to cellar'
    needs: build-rpm
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Download .rpm artifact'
        uses: actions/download-artifact@v4
        with:
          name: build-rpm
          path: build/${{ github.ref_name }}
      - name: 'Publish .rpm to cellar'
        run: ./scripts/publish-cellar.js ${{ github.ref_name }} rpm
        env:
          CC_CLEVER_TOOLS_RELEASES_CELLAR_BUCKET: ${{ secrets.CC_CLEVER_TOOLS_RELEASES_CELLAR_BUCKET }}
          CC_CLEVER_TOOLS_RELEASES_CELLAR_KEY_ID: ${{ secrets.CC_CLEVER_TOOLS_RELEASES_CELLAR_KEY_ID }}
          CC_CLEVER_TOOLS_RELEASES_CELLAR_SECRET_KEY: ${{ secrets.CC_CLEVER_TOOLS_RELEASES_CELLAR_SECRET_KEY }}

  publish-cellar-deb:
    name: 'Publish .deb to cellar'
    needs: build-deb
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Download .deb artifact'
        uses: actions/download-artifact@v4
        with:
          name: build-deb
          path: build/${{ github.ref_name }}
      - name: 'Publish .deb to cellar'
        run: ./scripts/publish-cellar.js ${{ github.ref_name }} deb
        env:
          CC_CLEVER_TOOLS_RELEASES_CELLAR_BUCKET: ${{ secrets.CC_CLEVER_TOOLS_RELEASES_CELLAR_BUCKET }}
          CC_CLEVER_TOOLS_RELEASES_CELLAR_KEY_ID: ${{ secrets.CC_CLEVER_TOOLS_RELEASES_CELLAR_KEY_ID }}
          CC_CLEVER_TOOLS_RELEASES_CELLAR_SECRET_KEY: ${{ secrets.CC_CLEVER_TOOLS_RELEASES_CELLAR_SECRET_KEY }}

  publish-aur:
    name: 'Publish to AUR'
    needs: publish-cellar-archives
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup SSH key'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Download build-linux artifact'
        uses: actions/download-artifact@v4
        with:
          name: build-linux
          path: build
      - name: 'Publish to AUR'
        run: ./scripts/publish-aur.js ${{ github.ref_name }}
        env:
          AUR_GIT_URL: ${{ vars.AUR_GIT_URL }}

  publish-homebrew:
    name: 'Publish to Homebrew'
    needs: publish-cellar-archives
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup SSH key'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Download build-linux artifact'
        uses: actions/download-artifact@v4
        with:
          name: build-macos
          path: build
      - name: 'Publish to Homebrew'
        run: ./scripts/publish-homebrew.js ${{ github.ref_name }}
        env:
          HOMEBREW_GIT_URL: ${{ vars.HOMEBREW_GIT_URL }}

  publish-dockerhub:
    name: 'Publish to Docker Hub'
    needs: publish-cellar-archives
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup SSH key'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Publish to Docker Hub (and related GitHub project)'
        run: ./scripts/publish-dockerhub.js ${{ github.ref_name }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKER_IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }}
          DOCKERHUB_GIT_URL: ${{ vars.DOCKERHUB_GIT_URL }}

  publish-exherbo:
    name: 'Publish to exherbo'
    needs: publish-cellar-archives
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup SSH key'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Publish to GitHub for exherbo'
        run: ./scripts/publish-exherbo.js ${{ github.ref_name }}
        env:
          EXHERBO_GIT_URL: ${{ vars.EXHERBO_GIT_URL }}

  publish-nexus-rpm:
    name: 'Publish .rpm to Nexus'
    needs: build-rpm
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Download .rpm artifact'
        uses: actions/download-artifact@v4
        with:
          name: build-rpm
          path: build/${{ github.ref_name }}
      - name: 'Publish .rpm to Nexus Repository'
        run: ./scripts/publish-nexus.js ${{ github.ref_name }} rpm
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_RPM_REPOSITORY: ${{ vars.NEXUS_RPM_REPOSITORY }}
  publish-nexus-deb:
    name: 'Publish .deb to Nexus'
    needs: build-deb
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Download .deb artifact'
        uses: actions/download-artifact@v4
        with:
          name: build-deb
          path: build/${{ github.ref_name }}
      - name: 'Publish .deb to Nexus Repository'
        run: ./scripts/publish-nexus.js ${{ github.ref_name }} deb
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_DEB_REPOSITORY: ${{ vars.NEXUS_DEB_REPOSITORY }}

  publish-winget:
    name: 'Publish .deb to Nexus'
    needs: publish-cellar-archives
    runs-on: windows-latest
    if: false
    steps:
      - name: 'Checkout sources'
        uses: actions/checkout@v4
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - name: 'Install Node.js dependencies'
        run: npm ci
      - name: 'Publish to Winget'
        shell: bash
        run: ./scripts/publish-winget.js ${{ github.ref_name }}
