name: Release

on:
  push:
    branches:
      - main
# on:
#   push:
#     tags:
#       - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ github.ref_name }}

  build-rpm:
    name: 'Build .rpm'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Download archives'
        uses: actions/download-artifact@v4
        with:
          pattern: archive-checksum-linux
      - name: 'List all artifacts'
        run: ls -la *

  build-deb:
    name: 'Build .deb'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Download archives'
        uses: actions/download-artifact@v4
        with:
          pattern: archive-checksum-linux
      - name: 'List all artifacts'
        run: ls -la *

  build-nupkg:
    name: 'Build .nupkg'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Download archives'
        uses: actions/download-artifact@v4
        with:
          pattern: archive-checksum-windows
      - name: 'List all artifacts'
        run: ls -la *

  publish-npm:
    name: 'Publish to npm'
    runs-on: ubuntu-latest
    steps:
      - name: 'Publish to npm'
        run: ls -la *

  publish-cellar-archives-checksums:
    name: 'Publish archives and checksums to cellar'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: ls -la *
  publish-cellar-rpm:
    name: 'Publish .rpm to cellar'
    needs: build-rpm
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: ls -la *
  publish-cellar-deb:
    name: 'Publish .deb to cellar'
    needs: build-deb
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: ls -la *
  publish-cellar-nupkg:
    name: 'Publish .nupkg to cellar'
    needs: build-nupkg
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: ls -la *

  publish-aur:
    name: 'Publish to AUR'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: ls -la *
  publish-brew:
    name: 'Publish to GitHub for Homebrew'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: ls -la *
  publish-dockerhub:
    name: 'Publish Docker Hub'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: ls -la *
  publish-exherbo:
    name: 'Publish to GitHub for exherbo'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: ls -la *

  publish-nexus-rpm:
    name: 'Publish .rpm to Nexus'
    needs: build-rpm
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: ls -la *
  publish-nexus-deb:
    name: 'Publish .deb to Nexus'
    needs: build-deb
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: ls -la *
  publish-nexus-nupkg:
    name: 'Publish .nupkg to Nexus'
    needs: build-nupkg
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: ls -la *
